version: "3.9"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: 1000
        GID: 1000
    environment:
      APP_ENV: dev
      XDEBUG_MODE: "off"   # "debug"
    volumes:
      - ./:/var/www:cached
    depends_on:
      db:
        condition: service_started
      rabbitmq:
          condition: service_healthy

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www:cached
      - ./nginx/symfony.conf:/etc/nginx/conf.d/default.conf:ro

  db:
    image: mysql:8.0
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: sVlPsF32847
      MYSQL_DATABASE: siroko_cart
      MYSQL_USER: siroko_user
      MYSQL_PASSWORD: sVlPsF3284
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # UI de gestión
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  rabbitmq_data:
