services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: public

    Siroko\Cart\Infrastructure\Persistence\Doctrine\Fixtures\:
        resource: '../../../src/Cart/Infrastructure/Persistence/Doctrine/Fixtures'
        tags: ['doctrine.fixture.orm']

    Siroko\Cart\Domain\Repository\:
        resource: '../../../src/Cart/Domain/Repository'

    Siroko\Cart\Infrastructure\Persistence\Doctrine\Repository\:
        resource: '../../../src/Cart/Infrastructure/Persistence/Doctrine/Repository'

    Siroko\Cart\Infrastructure\CommandBus\:
        resource: '../../../src/Cart/Infrastructure/CommandBus'

    Siroko\Cart\Infrastructure\Event\:
        resource: '../../../src/Cart/Infrastructure/Event'

    Siroko\Cart\Domain\Queue\:
        resource: '../../../src/Cart/Domain/Queue'

    Siroko\Cart\Infrastructure\Queue\:
        resource: '../../../src/Cart/Infrastructure/Queue'

    Siroko\Cart\Infrastructure\Service\:
        resource: '../../../src/Cart/Infrastructure/Service'

    Siroko\Cart\Infrastructure\CommandBus\Middleware\:
        resource: '../../../src/Cart/Infrastructure/CommandBus/Middleware/*'

    Siroko\Cart\Infrastructure\Api\Controller\:
        resource: '../../../src/Cart/Infrastructure/Api/Controller'
        tags: [ 'controller.service_arguments' ]

    Siroko\Cart\Domain\Repository\ProductRepository: '@Siroko\Cart\Infrastructure\Persistence\Doctrine\Repository\DoctrineProductRepository'
